"use client";

import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
import { GeistProvider, CssBaseline } from "@geist-ui/react";
import "./globals.css";
import Link from "next/link";
import Menu from "@/components/Menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GeistProvider>
          <CssBaseline /> {/* Normalizes styles */}
          <Menu />
          {children}
        </GeistProvider>
      </body>
    </html>
  );
}
